### ISSUE TITLE
One badge have two state

### ISSUE THREAD

**Issue by FelixINX** [remyvhw/slr#1]
Hello!

In the list of obstructions changes, the _badge_ with the status of the obstruction can sometimes have two positions. For example, I have not logged in for a while. During this period, an obstruction was created and then deleted.

The application then displays the two state in the same badge, and only one color is show (there are still two in the code, the first takes over).

![Example](https://i.imgur.com/QDKD6sF.png)

```
<span class="bg-transparent border text-xs py-1 rounded-full float-right border-green text-green border-red text-red"
  <span class="px-2">Nouveau</span>
  <!---->
  <span class="px-2">Supprimé</span>
</span>
```

Thanks!

**Comment by remyvhw** [comment]
Oops I didn't see the notification for this issue; sorry for the delay.
Thanks for bringing this up to me @FelixINX ! Do you think that, in such a scenario, only the `Supprimé` label should appear? Or it would be preferable to show both badges but with their correct respective colors?
Again, thank you for bringing this up to me! I'm sooooo happy to see SurLesRails is actually being used by others! 😃

**Comment by FelixINX** [comment]
I would suggest only the `Supprimé` label because having two labels might be confusing.

Thank you for creating SurLesRails, it's really useful! I'll have a suggestion for you: would it be possible to add the other APIs to the application? It's good to be able to see the Info Travaux but it's even better to be able to follow the albums, press releases, documents and news 😉 

- `https://rem.info/fr/api/document/{limit}/{offset}`
- `https://rem.info/fr/api/pressrelease/{limit}/{offset}`
- `https://rem.info/fr/api/album/{limit}/{offset}`
- `https://rem.info/fr/api/news/{limit}/{offset}`

**Comment by FelixINX** [comment]
Merci!

**Comment by remyvhw** [comment]
Je vais quand même essayer d'implémenter les documents/press release/albums/news éventuellement! ;)

**Comment by FelixINX** [comment]
@remyvhw Lorsque vous aurez le temps, c'est déjà parfait comme ça! :smile:
